destinations = ['New York','Tokyo','Singapore','Paris','Heaven']
print(destinations)
print(sorted(destinations))
print(destinations)
print(sorted(destinations,reverse=1))
print(destinations)
destinations.reverse()
print(destinations)
destinations.reverse()
print(destinations)
destinations.sort()
print(destinations)
destinations.sort(reverse=True)
print(destinations)
print(len(destinations))
print(destinations[-4])